#!/usr/bin/env python3
"""Counterexample-guided search for an affine-line cover of exponent pairs.

This is a discovery tool.  Any candidate it finds must subsequently be turned
into a finite exact certificate; a large checked box is not itself a proof.
"""

from __future__ import annotations

import argparse
import math
import os
import random
import sys
from pathlib import Path

import search_cover


def prime_factors(n: int) -> list[int]:
    out: list[int] = []
    d = 2
    while d * d <= n:
        if n % d == 0:
            out.append(d)
            while n % d == 0:
                n //= d
        d += 1 if d == 2 else 2
    if n > 1:
        out.append(n)
    return out


def primitive_root(p: int) -> int:
    factors = prime_factors(p - 1)
    for g in range(2, p):
        if all(pow(g, (p - 1) // q, p) != 1 for q in factors):
            return g
    raise AssertionError(p)


def discrete_log_bsgs(generator: int, target: int, order: int, p: int) -> int:
    """Return x in [0, order) with generator**x == target (mod p)."""
    width = math.isqrt(order) + 1
    baby = {}
    value = 1
    for exponent in range(width):
        baby.setdefault(value, exponent)
        value = value * generator % p
    giant_step = pow(pow(generator, width, p), -1, p)
    value = target % p
    for giant in range(width + 1):
        if value in baby:
            answer = giant * width + baby[value]
            if answer < order and pow(generator, answer, p) == target % p:
                return answer
        value = value * giant_step % p
    raise ValueError(f"target {target} is not in subgroup generated by {generator} mod {p}")


def signature(p: int, ord2: int, ord3: int) -> tuple[int, int, int, int, int]:
    h = math.lcm(ord2, ord3)
    root = primitive_root(p)
    generator = pow(root, (p - 1) // h, p)
    log2 = discrete_log_bsgs(generator, 2, h, p)
    log3 = discrete_log_bsgs(generator, 3, h, p)
    return h, log2, log3, ord2, ord3


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prime-limit", type=int, default=2_000_000)
    parser.add_argument("--max-h", type=int, default=1000)
    parser.add_argument("--count", type=int, default=80)
    parser.add_argument(
        "--period",
        type=int,
        help="use every candidate whose subgroup order divides this common period",
    )
    parser.add_argument("--seed-box", type=int, default=8)
    parser.add_argument("--seed-random", type=int, default=0)
    parser.add_argument("--scan-box", type=int, default=300)
    parser.add_argument("--scan-random", type=int, default=0)
    parser.add_argument("--rounds", type=int, default=100)
    parser.add_argument("--batch", type=int, default=1000)
    parser.add_argument("--timeout-ms", type=int, default=120_000)
    args = parser.parse_args()

    dep_path = Path(os.environ.get("TEMP", ".")) / "erdos203-pydeps"
    sys.path.insert(0, str(dep_path))
    from pysat.formula import IDPool  # type: ignore
    from pysat.solvers import Solver  # type: ignore

    candidates = []
    for p in search_cover.sieve(args.prime_limit):
        ord2 = search_cover.multiplicative_order(2, p)
        ord3 = search_cover.multiplicative_order(3, p)
        subgroup_order = math.lcm(ord2, ord3)
        if (
            subgroup_order <= args.max_h
            and (args.period is None or args.period % subgroup_order == 0)
        ):
            sig = signature(p, ord2, ord3)
            candidates.append((sig[0], p, *sig[1:]))
    candidates.sort()
    if args.period:
        candidates = [item for item in candidates if args.period % item[0] == 0]
    else:
        candidates = candidates[: args.count]
    print(f"using {len(candidates)} primes; density={sum(1/x[0] for x in candidates):.8f}")
    print("h,p,a,b,ord2,ord3")
    print(*candidates, sep="\n")

    pool = IDPool()
    solver = Solver(name="cadical195")
    choose: dict[tuple[int, int], int] = {}
    targets_by_prime: dict[int, list[int]] = {item[1]: [] for item in candidates}

    def variable_for(p: int, c: int) -> int:
        key = (p, c)
        if key in choose:
            return choose[key]
        variable = pool.id(f"c_{p}_{c}")
        # A fixed m residue modulo p selects at most one target fibre.
        for other in targets_by_prime[p]:
            solver.add_clause([-variable, -choose[p, other]])
        choose[key] = variable
        targets_by_prime[p].append(c)
        return variable

    # Translating all exponent pairs preserves the covering property.  Since
    # the p=5 functional is onto Z/4Z, normalize that target to zero.
    if any(item[1] == 5 for item in candidates):
        solver.add_clause([variable_for(5, 0)])

    added: set[tuple[int, int]] = set()

    def add_point(k: int, l: int) -> None:
        if (k, l) in added:
            return
        added.add((k, l))
        solver.add_clause(
            [
                variable_for(p, (a * k + b * l) % h)
                for h, p, a, b, ord2, ord3 in candidates
            ]
        )

    for k in range(args.seed_box):
        for l in range(args.seed_box):
            add_point(k, l)
    rng = random.Random(203)
    random_period = args.period or max(args.scan_box, 1)
    for _ in range(args.seed_random):
        add_point(rng.randrange(random_period), rng.randrange(random_period))

    for round_no in range(1, args.rounds + 1):
        result = solver.solve()
        print(f"round={round_no} constraints={len(added)} result={result}")
        if not result:
            return 2
        model = {literal for literal in solver.get_model() if literal > 0}
        chosen = []
        for h, p, a, b, ord2, ord3 in candidates:
            selected = next(
                (c for c in targets_by_prime[p] if choose[p, c] in model), 0
            )
            chosen.append(selected)
        uncovered = []

        def is_uncovered(k: int, l: int) -> bool:
            return not any(
                (a * k + b * l - c) % h == 0
                for c, (h, p, a, b, ord2, ord3) in zip(chosen, candidates)
            )

        for _ in range(args.scan_random):
            k = rng.randrange(random_period)
            l = rng.randrange(random_period)
            if is_uncovered(k, l):
                uncovered.append((k, l))
                if len(uncovered) >= args.batch:
                    break
        if len(uncovered) < args.batch:
            for k in range(args.scan_box):
                for l in range(args.scan_box):
                    if is_uncovered(k, l):
                        uncovered.append((k, l))
                        if len(uncovered) >= args.batch:
                            break
                if len(uncovered) >= args.batch:
                    break
        print(f"uncovered_in_scan={len(uncovered)}")
        if not uncovered:
            print("CANDIDATE")
            for c, item in zip(chosen, candidates):
                print((*item, c))
            return 0
        for point in uncovered:
            add_point(*point)
    return 3


if __name__ == "__main__":
    raise SystemExit(main())
